# Generated by Django 4.1.5 on 2023-03-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_actividad', models.CharField(max_length=30)),
                ('sector_asignado', models.CharField(max_length=20)),
                ('objetivo', models.CharField(max_length=100)),
                ('monto_planificado', models.IntegerField()),
                ('periodo', models.DateTimeField()),
            ],
        ),
    ]
